ihmeuw/vivarium_research

docs/source/glossary.rst, docs/source/index.rst, docs/source/models/cause.rst, docs/source/models/gbd2017/causes/diarrheal_diseases.rst, docs/source/models/gbd2017/causes/index.rst, docs/source/models/gbd2017/causes/latent_tuberculosis.rst, docs/source/models/gbd2017/causes/protein_energy_malnutrition.rst, docs/source/models/gbd2017/risks/high_body_mass_index_in_adults.rst, docs/source/models/gbd2017/risks/unsafe_water_source.rst, docs/source/models/risk_attributable_cause.rst
- Added stubs for things referenced in the docs and crosslinks to the stubs.  
- Added a glossary and some terms.
- Marked some todos.
- couple of typos.
=> Glossary, refs, and stubs

docs/source/models/gbd2017/causes/diarrheal_diseases.rst
Just an outline, comments welcome
=> Outline for Diarrheal Disease GBD 2017 Model

docs/source/models/gbd2017/causes/measles.rst
I added a "Model assumptions and limitations" section, and I added some detail to some of the todo's. I also added some hyperlinks and made a few other small edits.
=> Incorporate some feedback from documentation session

docs/source/models/gbd2017/concept_models/index.rst, docs/source/models/gbd2017/concept_models/vivarium_conic_lsff/index.rst, docs/source/models/gbd2017/concept_models/vivarium_conic_lsff/iron_fortification_concept_model.rst
The ..toctree:: directive is not finding my files in the `vivarium_conic_lsff` subfolder. I don't yet understand Sphinx well enough to fix it. Any suggestions?
=> Attempt to get table of contents to work

docs/source/models/gbd2017/causes/neural_tube_defects.rst
Starting to document Neural Tube Defects for the LSFF model
=> add stub for neural tube defects

docs/source/models/cause.rst
In the spirit of small PRs, I am asking for review on my description of incidence as a data source, although there is more to come for the incidence description (see to-do notes in file) as well as more to come for the transition section in general.
Overall, I would like to know if the text is clear, if the examples are helpful, and if it is accurate within the GBD/Vivarium context. Any other thoughts and suggestions are welcome as well :)
=> Data sources/transitions

docs/source/models/gbd2017/causes/neonatal_encephalopathy/index.rst, docs/source/models/gbd2017/causes/neonatal_jaundice/index.rst, docs/source/models/gbd2017/causes/neonatal_sepsis/index.rst
Starting to fill in the neonatal causes.
=> add case definitions for neonatal causes

docs/source/models/survival_analysis.rst
Hello! This is the start of the survival analysis page. For now, there are only headers and to-do notes in a separate survival analysis document. Please let me know if you think any sections are missing, unnecessary, out of order, etc. Also, if there is a better place to put the document please let me know. Thanks!
=> Survival analysis page

docs/source/models/gbd2017/causes/ischemic_heart_disease/index.rst
I added the summary disease description at the top. Should there be more information around prevalence, incidence, age groups?
=> Added a disease summary description.

docs/source/models/gbd2017/causes/cause_model_template.rst
Please review the section titles and the order of the sections, and post here if you want to suggest changes. I've put a few specific questions/concerns in special "Todo for template development" boxes within the .rst document itself.
=> Cause Model Template: outline and getting started instructions

docs/source/models/gbd2017/causes/causes.rst
I added a text description for DisMod in the non-fatal section of the page.
I would like feedback on its completeness and level of detail. I also would be curious to hear ideas about how to make it more readable. I am not sure writing out long paragraphs is the best way to communicate the information.
=> Filled out the section for DisMod in the non-fatal description.

docs/source/models/gbd2017/causes/diarrheal_diseases/index.rst
I might have had this in a previous PR, but it got lost when I moved diarrheal diseases into a sub folder. If so, I'm sorry for the redundancy!
=> updated description of GBD model for diarrheal diseases

docs/source/models/gbd2017/causes/neonatal_other/index.rst
I expanded the GBD description, and added a discussion of the issues we would face in trying to model this cause.
=> neonatal other: added discussion of challenges

docs/source/models/gbd2017/causes/neonatal_encephalopathy/index.rst
Sequel to PR https://github.com/ihmeuw/vivarium_research/pull/95 (adding a commit on top of that branch).
Just getting the restrictions table in the document for now. I'll rearrange the sections once we finalize the structure in the cause model template.
=> Neonatal Encephalopathy: add restrictions table

docs/source/model_design/risk_factors.rst
I created a new file since the outline we discussed today seemed different from the existing outlines for "Modeling Risk Exposure" and "Modeling Risk Effects."
Once this gets merged into master, we can each make a new branch and work separately on the individual sections within this file, and hopefully we can avoid merge conflicts.
=> new outline for modeling risk factors

docs/source/gbd2017_models/causes/ischemic_heart_disease/index.rst
- Add prevalence/dw for acute state based on sequelae prevalence.  
- Fix dw calc to scale by cause level prevalence.
=> Update formulates for disability and prevalence

docs/source/gbd2017_models/risk_attributable_causes/vitamin_a_deficiency/index.rst
Hi,
Here is my vitamin A deficiency doc draft, any improvement suggestion would be appreciated. Thank you
https://github.com/ihmeuw/vivarium_research/blob/feature/vitamin_a__deficiency/docs/source/gbd2017_models/risk_attributable_causes/vitamin_a_deficiency/index.rst
=> add draft doc of vitamin_a_deficiency

docs/source/gbd2017_models/risk_attributable_causes/chronic_kidney_disease/index.rst
I updated the description for the CKD model of the State Data table for EMR for moderate CKD. I forgot to delete the old description and found it after I merged to master.
=> Updated description for CKD moderate EMR.

docs/source/model_design/risk_factors.rst
Risk factor overview explanation.
Specific notes/questions, in addition to soliciting general feedback:
- should i make the low birth weight example more GBD-correct, and if so, @NathanielBlairStahn would you talk it through with me? Alternately, should I choose a less complex example?
- is it confusing or clarifying to go from individ --> population level?
- i need to figure out the indented bullet list spacing. it's annoying me right now but i thought i'd go ahead and PR so you can review the content.
=> Risk factor overview description

docs/source/gbd2017_models/risk_attributable_causes/iron_deficiency/index.rst
This branch is accidentally named causality, but it is really for iron deficiency anemia : ) 
I updated a few things and marked where we need to make decisions as a research team regarding modeling implementation strategy. If anyone has any thoughts on the approaches I proposed in the "to-do" notes in this document (or elsewhere), please leave your feedback!
Thanks.
=> Iron deficiency modeling strategy

docs/source/gbd2017_models/concept_models/vivarium_conic_lsff/concept_model.rst
Sequel to https://github.com/ihmeuw/vivarium_research/pull/169 (i.e. read that first)
=> LSFF #2: coverage algorithm

docs/source/gbd2017_models/concept_models/vivarium_conic_lsff/concept_model.rst
Sequel to 
https://github.com/ihmeuw/vivarium_research/pull/170 (read second), and
https://github.com/ihmeuw/vivarium_research/pull/169 (read first)
=> LSFF #3: determining effect of folic acid fortification

docs/source/gbd2017_models/concept_models/vivarium_sanofi_zenon/concept_model.rst
Give david step by step instruction about how to edit the concept model
=> Tell david what to do

docs/source/gbd2017_models/concept_models/vivarium_sanofi_zenon/concept_model.rst, docs/source/gbd2017_models/concept_models/vivarium_sanofi_zenon/data_output_shell_table with_updated_supops_and_strats.csv
This is adding in a version of the previous 'Desired Model Outputs' that has all desired stratifications and outputs, based on today's meeting. This file was created by Jessie and added by me.
=> Added in full desired model outputs table

docs/source/gbd2017_models/causes/ischemic_heart_disease/index.rst
Please let me know if I added incorrect information, or if I need to include more detail.
Thank you!
=> IHD model: Added information in the assumptions/limitations that risk factor affects transitions 1 and 3

docs/source/gbd2017_models/causes/lower_respiratory_infections/index.rst
add note about birth prevalence before we forget :)
=> LRI birth prevalence note for followup

docs/source/gbd2017_models/concept_models/vivarium_conic_lsff/concept_model.rst
Please excuse the crappy formatting, I just wanted to get this posted ASAP and will work to improve the design while waiting for any feedback on the content. Thanks :)
=> LSFF how to apply iron intervention effects

docs/source/gbd2017_models/concept_models/vivarium_conic_lsff/concept_model.rst
One of the references sent by our colleagues at BMGF made me realize that we were interpreting the iron concentration listed by the global fortification data exchange incorrectly; this PR reflects the necessary changes. This change will end up increasing the impact we have through the iron fortification effect on low birth weight.
=> LSFF iron dose calculation update

docs/source/model_design/risk_factors.rst
I'm planning to add in a sim science specific section as well, but wanted feedback on what is included so far before starting. Thanks in advance!
=> Causal intro update

docs/source/gbd2017_models/concept_models/vivarium_conic_lsff/concept_model.rst
This is the pseudo-code that James sent to explain how he implemented the intervention in vivarium to produce our model outputs.
=> LSFF pseudo-code for vitamin a intervention implementation

docs/source/gbd2017_models/concept_models/vivarium_conic_lsff/concept_model.rst
Change bolded text into actual section headings.
=> LSFF: section headings

docs/source/concept_models/vivarium_conic_lsff/concept_model.rst
Just changing some section levels and adding some links
=> LSFF: restructure concept model sections

docs/source/gbd2019_models/causes/neoplasms/multiple_myeloma/index.rst
I created an outline for the GBD 2019 Multiple myeloma cause model, based on GBD 2017 model created by @yaqi7.
=> Adding GBD 2019 MM model outline

docs/source/gbd2019_models/causes/neoplasms/multiple_myeloma/index.rst
I am adding a GBD 2019 MM Disease Overview, based on the GBD 2017 model. I am looking for updated capstone and 2019 data to include in the overview, as relevant.
=> Adding MM Disease Overview and related references

docs/source/gbd2017_models/causes/neoplasms/stomach_cancer/cancer_model.rst
Will updated more after swissre meeting to discuss screening (we might not PC state if they decide not to use endoscopy screening)
=> added forecast filepth and updated prev_PC equation

docs/source/gbd2017_models/causes/neoplasms/lung_cancer/cancer_model.rst
=> Lung cancer EMR and YLD fixes

docs/source/concept_models/vivarium_swissre_cervicalcancer/concept_model.rst
In talking with collijk, it seemed as though these corrections need
to be made to the concept model doc.
=> Correct assumed typos/omissions re: hrHPV vaccine effects

docs/source/gbd2017_models/causes/neoplasms/stomach_cancer/cancer_model.rst
Added extra notes in the state tables to describe prev_c and prev_pc states as per Abie's advice!
=> added notes in state table

docs/source/concept_models/vivarium_swissre_stomachcancer/concept_model.rst
1. I will be adding data source table to consolidate all references and data sources
2. I will re-create output data shell in the rst file
3. Add assumptions and limitations to the section
4. Add validation and verification
=> edited screening branch numbers

docs/source/gbd2017_models/risks/smoking/index.rst
=> Smoking pack year and ysq exposures update to gbd 2019

docs/source/concept_models/vivarium_swissre_colorectalcancer/concept_model.rst
To-do:
1. Update baseline screening coverage.
2. Add distribution for combined risk factors.
=> update colorectal cancer model parameters

docs/source/gbd2019_models/causes/ihd/index.rst
Hello! Testing out the PR system and adding in the outline for the GBD 2019 IHD model.
=> Adding outline for GBD 2019 IHD model

docs/source/gbd2019_models/causes/ischemic_stroke/index.rst
Hi both! I have created the outline for ischemic stroke and filled out the disease description section.
=> First commit for ischemic stroke - filled out disease desc section

docs/source/gbd2019_models/causes/ischemic_stroke/index.rst
@catherineojohnson, I had two questions:
1. I was only to find any definitions for incidence for ischemic stroke in the case definitions tool. Should any definitions for prevalence or other measure be included for ischemic stroke?
2. Should the modified Rankin score for "Stroke, severe plus cognition problems" be 4, 5?
=> Added GBD 2019 modeling strategy section.

docs/source/concept_models/vivarium_sanofi_multiple_myeloma/concept_model.rst
I updated this section based on the online collaborative editing concept model shared with Sanofi.l
=> Updating MM modeling aims and objectives.

docs/source/gbd2019_models/risk_exposures/fpg/index.rst
@aflaxman Looking ahead to the next section, do we need to have a risk exposure model diagram?
=> Added GBD modeling strategy for FPG.

docs/source/model_design/concept_model/ensemble_distributions/index.rst
This is an outline for a page about ensemble distributions in GBD. I put it under the "Vivarium Model Considerations and Best Practices" section -- let me know if that seems like a good location. Also let me know if you think there should be other sections in the document.
=> Add page for Ensemble Distributions in Vivarium Model Considerations

docs/source/gbd2019_models/risk_exposures/sbp/index.rst
@aflaxman Is there any additional information that is needed for the vivarium research strategy section (such as any other data description tables or a risk exposure model diagram)?
=> Added vivarium research strategy

docs/source/gbd2019_models/risk_exposures/bmi/index.rst
@aflaxman Same question as for SBP -- Is there any additional information that is needed for the vivarium research strategy section (such as any other data description tables or a risk exposure model diagram)?
=> Added vivarium research strategy for BMI

docs/source/model_design/concept_model/ensemble_distributions/index.rst
Added a brief introduction describing what an ensemble distribution is, and a section listing the base distributions used by GBD, with links to the R repo on Stash and the Python repo used by Vivarium Public Health.
=> Ensemble distribution intro

docs/source/gbd2019_models/causes/lower_respiratory_infections/index.rst
Added description of GBD 2019 modeling
=> GBD 2019 LRI: added gbd modeling description

docs/source/model_design/concept_model/ensemble_distributions/index.rst
Added the beginning of a section explaining how ensemble distribution modeling works in GBD. It would be good to get other people's eyes on this to make sure what I'm saying so far is accurate.
=> Ensemble distributions - start explaining math

docs/source/model_design/concept_model/ensemble_distributions/index.rst
Here's the section describing how to sample from a mixture distribution. It would be good to have both researchers and engineers take a look to make sure everything makes sense.
=> Ensemble distribution sampling

docs/source/concept_models/vivarium_sanofi_multiple_myeloma/concept_model.rst
This is a strategy for what I am considering the minimal treatment coverage algorithm.
I want to confirm with Manoj how we should handle subsequent treatment with isa if already treated with isa (I have proposed two different directions in this PR).
My main concern with this strategy as-is is our ability to apply reasonable efficacy data between the isa group and the "other" group. I am now shifting my focus to going to go through the different treatment comparisons that exist in the literature to see if we can tease out something reasonable.
=> MM treatment model strategy detail

docs/source/model_design/concept_model/ensemble_distributions/index.rst
This PR adds some descriptions of what's in the GBD R repo and the Vivarium Python repo for ensemble distributions, in an attempt to address several points raised by @beatrixkh in PR https://github.com/ihmeuw/vivarium_research/pull/468.
=> Ensemble distribution code descriptions

docs/source/gbd2019_models/causes/diarrheal_diseases/index.rst
Added disease description, pulling from 2017 documentation
=> GBD 2019: Diarrhea disease description

docs/source/gbd2019_models/risk_attributable_causes/protein_energy_malnutrition/index.rst
Page stub + headings for PEM in GBD 2019
=> GBD 2019: PEM. Added page stubs

docs/source/index.rst, docs/source/model_design/intervention_features.rst, docs/source/model_design/risk_factors.rst
This PR cleans up a few syntax errors that were causing annoying warnings when running `make html`.
=> Fix syntax errors in `source/index.rst`, `risk_factors.rst` and `intervention_features.rst`

docs/source/gbd2019_models/risk_attributable_causes/protein_energy_malnutrition/index.rst
Very minimal info re: PEM sequelae and gbd modeling approach.
=> PEM sequelae + modeling info

docs/source/concept_models/vivarium_sanofi_multiple_myeloma/concept_model.rst, docs/source/gbd2019_models/causes/neoplasms/multiple_myeloma/cancer_model.rst
Sync technical report and Vivarium research page.
=> Clean up multiple myeloma research document

docs/source/concept_models/vivarium_ciff_sam/concept_model.rst
Added placeholders for the model components we still need documentation for.
Questions for @Ninicorn, @plinds, and @aflaxman: Is there existing documentation that I missed for any of the things I listed but don't have links? Are there any additional model components that I haven't listed?
=> CIFF SAM Concept Model: Add titles for remaining model components

docs/source/gbd2020_models/risk_attributable_causes/wasting/index.rst
Added code for pulling GBD 2019/2020 data for PEM
=> added PEM2019 and code to call GBD draws

docs/source/gbd2019_models/risk_exposures/low_birthweight_short_gestation/index.rst
Sequel to https://github.com/ihmeuw/vivarium_research/pull/576
=> LBWSG 2019 exposure: Add TOC and risk factors methods appendix reference

docs/source/gbd2019_models/risk_exposures/low_birthweight_short_gestation/index.rst
Sequel to https://github.com/ihmeuw/vivarium_research/pull/581
Add a section noting that the LBWSG prevalence data in GBD 2019 doesn't add up to 1 like expected, and explain what to do about it.
=> LBWSG 2019 exposure: Explain how to fix GBD's bad prevalence data

docs/source/intervention_models/wasting_treatment/index.rst
=> correct a missed typo

docs/source/intervention_models/wasting_treatment/index.rst
Added description from our conversations yesterday about not modelling treatment in the neonatal age groups.
=> added age restriction for treatment

docs/source/concept_models/vivarium_us_cvd/concept_model.rst
Updating demographic section with additional detail about the desired stratification of simulants. Please let me know if additional details are needed.
=> updating demographic information

docs/source/intervention_models/wasting_treatment/index.rst
This PR is a cleanup of the formatting, clarification of how to apply intervention effects, and a change to the equation to derive r2ux (shown in the screenshots below)
=> [new modeling strategy] Update wasting treatment model for clarity, fix suspected error

docs/source/concept_models/vivarium_ciff_sam/concept_model.rst
Adding start and end dates for the simulation and interventions in the CIFF SAM concept model.
Again, lots of spurious whitespace changes, so you should hide them.
=> CIFF SAM intervention timing

docs/source/intervention_models/wasting_treatment/index.rst
I added some clarification and limitations about the "duration" parameters currently used in our treatment model and added some additional related assumptions.
This PR does not change our modeling strategy or any data used in the model.
=> Wasting treatment documentation clean up

docs/source/gbd2019_models/risk_effects/ldl/index.rst, docs/source/gbd2019_models/risk_effects/sbp/index.rst
fixing equation for applying RR to incidence
=> correcting equation for applying RR to incidence

docs/source/concept_models/vivarium_ciff_sam/concept_model.rst, docs/source/gbd2019_models/risk_risk_correlation/maternal_bmi_birthweight/index.rst
I put this page in the risk correlation section rather than risk effects section because we model the crude rather than causal impact of maternal BMI on birthweight.
=> maternal BMI and birthweight association

docs/source/concept_models/vivarium_ciff_sam/concept_model.rst
Just reducing clutter on this page and also linked to the hub page where Paulina is tracking live model status
=> CIFF reformat model build versions to table

docs/source/gbd2019_models/causes/maternal_disorders/index.rst, docs/source/other_models/pregnancy/index.rst
The original PR was approved, but accidentally closed automatically  when I merged and deleted a dependent branch. Here it is again :)
=> Reopened pregnancy update PR 

docs/source/concept_models/vivarium_iv_iron/maternal_model/concept_model.rst, docs/source/gbd2019_models/risk_exposures/maternal_bmi_hgb/index.rst, docs/source/gbd2019_models/risk_risk_correlation/maternal_bmi_hgb_birthweight/index.rst
Sorry for a larger PR! This is kind of a template strategy for the assumed structure of the data that we receive from the BMGF, but should be easily adapted if the data is in a slightly different form as well.
=> modeling strategy proposal from bmi, hgb, bw

docs/source/concept_models/vivarium_iv_iron/concept_model.rst, docs/source/concept_models/vivarium_iv_iron/maternal_model/concept_model.rst, docs/source/intervention_models/maternal_supplementation/index.rst
These changes should not affect anything that has already been implemented (just updates to intervention implementation)
=> IV iron update according to BMGF feedback

docs/source/intervention_models/breastfeeding_promotion/index.rst
Conversion of risk difference to relative risk with scaling of calculated confidence interval to account for clustering.
=> Breastfeeding risk difference to relative risk

docs/source/gbd2019_models/risk_effects/diarrheal_diseases/index.rst
Here's what the equations look like formatted:
=> update diarrheal diseases on wasting PAF equation

docs/source/concept_models/vivarium_iv_iron/child_model/concept_model.rst, docs/source/concept_models/vivarium_iv_iron/child_model/output_table.csv, docs/source/concept_models/vivarium_iv_iron/maternal_model/concept_model.rst
=> IV iron child sim output table

README.rst
=> Update a step in contributing

docs/source/concept_models/vivarium_csu_multiple_myeloma_2/concept_model.rst
Reorganizes the content slightly and adds a link to a new Sharepoint folder that has more information than the slide deck I originally linked.
=> MM concept model - add link to Sharepoint folder

docs/source/concept_models/vivarium_csu_multiple_myeloma_2/concept_model.rst, docs/source/intervention_models/multiple_myeloma_treatment/index.rst
Blank template, no content yet.
I am merging this into the `cleanup/rename-mm-folders` branch from https://github.com/ihmeuw/vivarium_research/pull/808 to avoid annoying merge conflicts. Even though it says no reviews are needed to merge, two reviews will still be needed once that branch gets merged into main.
=> Multiple myeloma treatment model template

docs/source/intervention_models/multiple_myeloma_treatment/index.rst
Adds table showing classes of drugs for MM treatment and a table showing proposed treatment categories for Phase 2 MM simulation.
=> Multiple Myeloma Treatment: Treatment regimen categories

docs/source/gbd2019_models/causes/maternal_disorders/index.rst
This is a fix for the temporary solution, but it's a low priority since it will end up making just a slight difference!
=> Solution for negative maternal disorders YLDs

docs/source/concept_models/vivarium_iv_iron/maternal_model/output_table.csv, docs/source/gbd2019_models/risk_effects/maternal_hemorrhage/index.rst
I believe that this has not already been built by the software engineers, so we shouldn't need a new ticket for it, but SWE feedback would be helpful!
=> hemorrhage risk effect update

docs/source/concept_models/vivarium_iv_iron/child_model/concept_model.rst, docs/source/gbd2019_models/causes/diarrheal_diseases/index.rst, docs/source/gbd2019_models/causes/lower_respiratory_infections/index.rst
I think these updates should address our validation issues for diarrheal diseases and LRI that we have been seeing and would like them to be incorporated into the existing IV iron child sim.
Please let me know if there are any questions about this strategy that I can help clarify.
=> cause model updates to fix validation issues

docs/source/gbd2019_models/risk_risk_correlation/maternal_bmi_hgb_birthweight/index.rst
Here is the rendered table for ease of review
=> Add detail on how to calculate hgb/bmi/bw association

docs/source/concept_models/vivarium_iv_iron/maternal_model/concept_model.rst, docs/source/intervention_models/maternal_supplementation/index.rst
This is consistent with the engineering implementation -- not changes need to be made!
=> Doc clean up for iv iron sim intervention details

docs/source/intervention_models/iv_iron_antenatal/index.rst, docs/source/intervention_models/iv_iron_postpartum/index.rst, docs/source/other_models/pregnancy/index.rst
This is consistent with the engineering implementation - not changes need to be made!
=> Uncertainty clarification

README.rst
My environment was using 3.8, not sure whether it still works with 3.6.
=> Python version 3.6->3.8 in environment setup

docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
=> ENH: add details about simple twin model

docs/source/concept_models/vivarium_csu_multiple_myeloma/concept_model.rst, docs/source/concept_models/vivarium_csu_multiple_myeloma_2/concept_model.rst
I haven't documented the standard outputs -- YLDs, YLLs, etc.
My assumption is that we are no longer interested in the registry observer/output.
=> Document treatment and survival output format

docs/source/intervention_models/multiple_myeloma_treatment/index.rst, docs/source/intervention_models/multiple_myeloma_treatment/verify_model_probabilities.py
Based on discussion of starting with the naive prediction models, I have supplied them both in CSV (easier to load) and pickle (more similar to how the later models will be loaded, if we stick with the current plan) formats.
=> Document naive MM treatment prediction models

docs/source/gbd2020_models/causes/measles/index.rst
Very minor updates - primarily I am practicing making edits and commits and working on figuring out git
=> Adding more todo's and minor updates

docs/source/concept_models/vivarium_csu_multiple_myeloma_2/concept_model.rst
Code PRs:
- [run off a custom branch with modifications](https://github.com/ihmeuw/vivarium_research_multiple_myeloma/pull/17).
- [run off `main` after SEs had made fixes](https://github.com/ihmeuw/vivarium_research_multiple_myeloma/pull/22).
=> Model 3 V&V log

docs/source/gbd2019_models/hemoglobin_anemia_and_iron_deficiency/risk_effects/index.rst, docs/source/other_models/pregnancy/index.rst
Please let me know if there are any questions/anything unexpected here! Thanks
=> Update stillbirth model in accordance with SWE implementation plan

docs/source/concept_models/vivarium_ciff_sam_2/concept_model.rst
Just some edits for clarity :)
=> Wasting paper concept model doc edits

docs/source/model_design/concept_model/results_processing_steps/index.rst
Please feel free to add to this page!!
=> Vivarium best practices: results processing and v&v tips

docs/source/model_design/concept_model/monte_carlo_uncertainty/index.rst
@SylLutze and I just met to talk through this, so I thought it would be worth writing up to have as a resource. I left to-do notes to link to other resources so if anyone has any in mind that may be good fits, please let me know!
=> vivarium best practices: monte carlo uncertainty

docs/source/gbd2019_models/causes/heart_failure/index.rst, docs/source/gbd2019_models/risk_effects/sbp/index.rst
I had neglected to do this earlier so updating now with the information about heart failure.
=> Updating the SBP effects docs with HF information

docs/source/concept_models/vivarium_us_cvd/concept_model.rst
Some updates from Steve: 
- Treatment assignments are separated into inertia and then assignment into type of medication 
- Clarifications on initialization of appointments 
- Marking the out of date vivarium pages as out of date
=> Assorted updates from Steve

docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Just things I noticed as I read through the concept model.
We need to make an engineering ticket for the last name assignment by relationship!
=> Make minor edits to PRL concept model

docs/source/gbd2019_models/causes/neoplasms/multiple_myeloma_2/cancer_model.rst, docs/source/intervention_models/multiple_myeloma_treatment/index.rst
I had forgotten to make a PR for these changes, which are corrections I discovered while writing the assumptions and limitations in the technical report. These are nowhere near comprehensive; there are probably still many things in the technical report not reflected in documentation.
=> Correct assumptions and limitations of Phase 2

docs/source/gbd2020_models/risk_attributable_causes/wasting/index.rst
As determined and implemented by @hussain-jafari!
=> Note on wasting transition truncated normal distribution

docs/source/concept_models/vivarium_us_cvd/concept_model.rst
I also added the multiplier column in this PR
=> Clarify how adherence and treatments interact at initialization

docs/source/gbd2019_models/causes/diarrheal_diseases/index.rst, docs/source/gbd2019_models/causes/lower_respiratory_infections/index.rst
Note: this is documentation catch-up and this modeling strategy has already been implemented for the IV iron simulation.
We made the same updates to the lower respiratory infections, so I am planning to get feedback on this update and then replicate it on the LRI page afterwards.
=> Diarrheal diseases cause model updates

docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
I'm not going to merge this one before Beatrix reviews 😅
=> Re-revise PUMA edge case handling

docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Hi all, I have tried to do this in the simplest way possible to see what adding a new survey would be like at the easiest based on what we have. My hope is future surveys would fit more nicely into our "by mode" framework, but maybe that is not realistic. 
Let me know if this seems reasonable to you with the assumptions or not.
=> Adding CPS observer

docs/source/concept_models/vivarium_ciff_sam_2/concept_model.rst
This PR is an update based on recent conversations with Hussain that have already been implemented and do not contain new information that needs to be implemented.
=> Wasting paper sim stratification updates and clarification

docs/source/concept_models/vivarium_ciff_sam_2/concept_model.rst
Yay - will plan to briefly review in tomorrow's RT meeting, but otherwise I think we're all set to move forward :)
=> Wasting paper model 1 V&V tracking

docs/source/concept_models/vivarium_ciff_sam_2/concept_model.rst
I did not make a ticket for the bugfix because Hussain already has.
=> wasting paper model 2.0 v and v

docs/source/concept_models/vivarium_us_cvd/concept_model.rst
Note: the link does not work right now, once Steve uploads it I can edit if needed.
=> Updating LDL values and clarifying language

docs/source/concept_models/vivarium_ciff_sam_2/concept_model.rst
Updates from the RT/SE check-in!
=> Wasting concept model updates from RT/SE check-in

docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
I wasn't too successful at finding the perfect data source.
I've tried to "show my work" with the background research so that we will have it if we decide to revisit this component, but I ended up going with a pretty simple approach in the sim.
=> Document mailing address

docs/source/concept_models/vivarium_census_synthdata/concept_model.rst
Data analysis PR: https://github.com/ihmeuw/vivarium_research_prl/pull/8
Originally was planning to update only the unemployment number, but the military number appears to be off by 10x.
=> Update proportions of special employers

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Sorry - this is identical to before but because of how I organized the branches once I merged omissions, this ended up making a second PR.
=> Adding Duplicates 

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
This was pointed out in code review of the implementation; I think how I had written it here understated the assumption.
=> Clarify limitation of employment change on move

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
This section was primarily documented with sample code, much of which was outdated/misleading; I have replaced that with prose and explained how the race/ethnicity for sampling is determined.
=> Clean up last name, include race/ethnicity logic

docs/source/models/risk_exposures/fpg/index.rst
Updating the docs to match decisions made and implemented in the model already.
=> Adding FPG bounds

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
- Also changing data types to be all strings 
- and clarifying typographic noise parameters
=> Clarify noise order, add OCR and typographic noise

docs/source/models/risk_correlation/sbp_ldlc_fpg_bmi/index.rst
I know this workbook is super long but might be good to have someone else's eyes on it! 
https://github.com/ihmeuw/vivarium_research_nih_us_cvd/blob/main/PAF_interactive.ipynb
=> Joint PAFs for CVD

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Also, some unrelated small cleanup.
=> Change percent to probability in noise functions

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
This should eventually live in the pseudopeople docs; putting it here for now so we can give something to the engineers quickly.
=> Describe date subsetting in each observer

docs/source/models/concept_models/vivarium_nutrition_optimization/pregnancies/concept_model.rst
Updates to reflect discussion in RT/SE check-in
=> Preg model versioning

docs/source/models/concept_models/vivarium_nutrition_optimization/pregnancies/concept_model.rst
I'm thinking we can go over this at the next RT/SE check-in. This is a suggested outline intended to start the conversation and is not set in stone, so we can definitely make changes based on what will make sense for implementation.
=> Pregnancy model versions table

docs/source/models/concept_models/vivarium_nutrition_optimization/pregnancies/concept_model.rst
Simulated maximum coverage will be 100% and _emulated_ maximum coverage will be ANC1. Updating sim docs to reflect this.
=> Fix to pregnancy intervention maximum coverage levels

docs/source/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.rst
As discussed in last week's nutrition optimization RT check-in meeting. I am not seeing Latera on github to review this. Can someone else please add him as a reviewer?
=> N.O child task tracking assignments

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Adding a bit more explanation to why dates are formatted the way that they are.
=> Add format of survey date, cite sources

docs/source/models/risk_exposures/child_growth_failure/wasting_state_exposure/index.rst
Note that these parameters/equation are structured a little funny by rescaling between rates and durations, but I structured it this way to minimize changes to how the equations were already implemented.
=> Update to combined protocol wasting intervention parameters

docs/source/models/concept_models/vivarium_us_cvd/concept_model.rst
After talking with Rajan and Hussain, I had missed making an update in one of the boxes for the SBP treatment ladder. No changes to the planned approach in this PR.
=> Fixing therapeutic inertia error

docs/source/models/causes/malaria/index.rst
Abie had some comments in the concept model meeting around malaria's duration and our rate based approach. Documenting those so we remember and can go back to this later if desired.
=> Adding duration limitation to Malaria

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
Add 'year' or 'tax_year' to the list of column names for each dataset. 
Jira ticket: https://jira.ihme.washington.edu/browse/SSCI-1465
=> Add year columns to datasets in concept model

docs/source/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.rst
=> Updates to N.O. child model versions

docs/source/models/risk_attributable_causes/wasting/gbd_2020_transition_model/index.rst, docs/source/models/risk_exposures/child_growth_failure/wasting_state_exposure/index.rst
Typo got copied over from old docs to new docs and I fixed it in both places
=> Fix wasting transition rate typo identified by Hussain

docs/source/models/causes/malaria/index.rst
Updated to reflect strategy that will be used in the sim after discussing with Hussain
=> Update malaria docs to reflect implemented strategy

docs/source/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.rst
The rates are looking perfect, yay :) 
But it does not look like wasting treatment is affecting them as expected - can we please make sure that implementation reflects the expected behavior documented here: https://vivarium-research.readthedocs.io/en/latest/models/intervention_models/wasting_treatment/compas_trial_wasting_treatment/index.html
Note that the C_MAM, C_SAM, E_SAM, and E_MAM parameters used here should be using the linked CSVs rather than values generated within the sim.
=> N.O. child model 6 V&V tracking

docs/source/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.rst
I will continue to look into all of the exact values here, but I wanted to make these initial weird findings known as I continue to investigate. Let me know if it would be helpful to talk through any of this. Thanks!
=> N.O. child model 5.0bugfix vv notes

docs/source/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.rst
Just wanted to get the current known outstanding issues in the child model written down as I understand it at the end of the day today! Basically we have edits to make to model 3, 4, 5, and 6 - we know what to do for models 3 and 4, but haven't figured out what the issues are with 5 and 6 yet. 
Let me know if anyone has any edits to this list! Thanks :)
=> N.O. child model status

docs/source/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.rst
Probably could have just included this in the last PR but oh well.
=> V&V for Pregnancy BMI and Anemia to Birthweight

docs/source/models/risk_exposures/maternal_bmi_hgb/index.rst
There are only new links for Pakistan because I just appended Pakistan to the results for the other parameters
=> Updated BMI links for Pakistan

docs/source/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.rst
Ali - let me know if you think it's important to also check this in the interactive sim. It seemed like it was correct from model outputs but we can double check if needed.
=> V&V from Child Model 9

docs/source/models/risk_effects/child_growth_failure/cgf_2021/index.rst, docs/source/models/risk_exposures/child_growth_failure/underweight/index.rst
Add links to `lookup.csv` and `pafs.csv` for Pakistan and Nigeria to the appropriate documentation pages
Related JIRA ticket: https://jira.ihme.washington.edu/browse/SSCI-1500
=> Add links to CGF calculations for Pakistan and Nigeria

docs/source/models/concept_models/vivarium_nutrition_optimization/pregnancies/concept_model.rst
Note, we are still not ready for production runs yet as we need to first look into some updates for MMS effect sizes
=> Update pregnancy scenarios

docs/source/model_design/vivarium_model_components/GBD_disease_health/index.rst, docs/source/model_design/vivarium_model_components/impairments/index.rst, docs/source/model_design/vivarium_model_components/index.rst
I struggled with the title for the GBD impairment/cause/health states/sequelae page so feel free to suggest something better!
=> Adding outlines for 2 impairment pages

docs/source/models/intervention_models/crm_mgmt/vivarium_polypill.rst
The purpose of this PR is to document details provided by Greg. No changes to the simulation will be made, we are just adding context and references.
=> Adding additional polypill dosing details

docs/source/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.rst
Two remaining issues in this run:
1. Underestimation of untreated SAM to MAM transition rate for 1-5 month age group
2. Underestimation of MAM to mild transition rate for 6-59 month age group
Let me know if anyone would like to discuss! Thanks
=> Model 10.3 V&V summary

docs/source/models/concept_models/vivarium_us_cvd/concept_model.rst
This is using fake data and does not include the on time step changes to the model. We expect to see changes "wash out" in V&V.
=> State medication variation at initialization only 

docs/source/models/intervention_models/wasting_treatment/compas_trial_wasting_treatment/index.rst
Note - this PR is simply updating documentation to match our implementation. No changes to our data or models are required as a result of this PR.
=> Update to time to recovery parameter values

docs/source/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.rst
Bugs addressed in this run were resolved! There may be something else going on with mortality rates than what I have been suspecting though... will follow up when our model versioning catches up
=> Model 11.2 v and v summary

docs/source/models/concept_models/vivarium_us_cvd/concept_model.rst
Hello, after confirming with Greg, we are removing a good number of the observers - specified in the observer table - and doing some timing test runs. Steve let's touch base on what you would recommend for scenarios and locations. Happy to do bigger or smaller based on what you would recommend.
=> CVD timing test runs

docs/source/model_design/general_reference_material/bliss/index.rst
This PR adds recommended readings for the formerly named 'Knowledge Share' section. I found two new articles not yet cited by this page, that I think everyone should check out if you haven't read them yet! [This paper](https://jech.bmj.com/content/jech/76/9/823.full.pdf?casa_token=C7iZK5EoMhUAAAAA:cvfmSjOPVtREW68LbySS7gzxrNENSE_achybw7trYyaC__igW-9B6nj02oGpmNEQIFderiUqPzAY) for gender-inclusive writing about pregnancy and [this one (that Os recommended)](https://bmcpregnancychildbirth.biomedcentral.com/articles/10.1186/s12884-020-03166-6) about men (cis and trans),  transmasculine people, or other folks that aren't cis women, dealing with pregnancy loss. 
I'm currently trying to work my way through [this reference list](https://jira.ihme.washington.edu/secure/attachment/115842/image%20%287 …
=> Add to BLISS "Recommended Resources" list 

docs/source/model_design/general_reference_material/bliss/index.rst
- Flesh this out a bit, including explaining better how it works for figures and tables
- Make flow better with other sections
- Add more headings
=> Revise BLISS results section

docs/source/model_design/general_reference_material/bliss/index.rst
Took a pass at this, let me if this is what others had in mind or what needs to be added.
=> Adding section about political aspects of language to BLISS

docs/source/model_design/general_reference_material/bliss/index.rst
JIRA ticket: https://jira.ihme.washington.edu/browse/SSCI-1683 
NB - I also removed our to-do for Do's and Don'ts, but happy to add it back in if others find it important to include
=> Add section on research considerations before following our BLISS guide 

docs/source/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.rst
Ali - planning to discuss the ordering of these in our meeting today. Capturing the general model specs but can shuffle task order later.
=> Adding targeted SQ-LNS wave 3 model run specs

docs/source/models/intervention_models/lipid_based_nutrient_supplements/index.rst
Still a lot of to-dos but this should reflect our conversation
=> Update SQ-LNS targeting docs

docs/source/model_design/general_reference_material/bliss/index.rst
JIRA ticket: https://jira.ihme.washington.edu/browse/SSCI-1684 
This got a little more verbose than I wanted, but I think it's an important point to make that these results abbreviations guidelines will be a lot simpler with more specific data reporting standards!
=> Add a caveat to our results indicator abbreviation section that there are exceptions

docs/source/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.rst
Documentation of this PR in vivarium research: https://github.com/ihmeuw/vivarium_research_nutrition_optimization/pull/134
=> DHS CGF correlation data will be national

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst
[JIRA ticket](https://jira.ihme.washington.edu/browse/SSCI-1665)
=> Update the order that noises are applied in PRL concept model

docs/source/model_design/general_reference_material/bliss/race_ethnicity/index.rst
As I was making the JIRA tickets for this, I realized there were some typos.
=> Fix typos in outline for race and ethnicity guide

docs/source/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.rst
=> Update versioning of child model for wave III

docs/source/model_design/programming_vivarium/overview_engineering_files/index.rst
I also included the engineers as reviews to check some of my work here. This is not intended to be enough information to actually do a lot of anything - just higher level background and reference information. I will also create pages for running the sim, etc. that have more depth and instructions.
=> Creating page on engineering files

docs/source/models/concept_models/vivarium_nutrition_optimization/pregnancies/concept_model.rst
=> NO pregnancy model 11.2 observer V&V update

docs/source/model_design/general_reference_material/ensemble_distributions/index.rst
Checked in this PR: https://github.com/ihmeuw/vivarium_research_nutrition_optimization/pull/149
=> Confirm that XMIN and XMAX values do not affect distribution means

docs/source/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.rst
SQLNS effect sizes should be updated in accordance with this PR https://github.com/ihmeuw/vivarium_research_nutrition_optimization/pull/154
=> 13.1 sqlns rerun request

docs/source/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.rst, docs/source/models/risk_effects/child_growth_failure/cgf_2021/index.rst, docs/source/models/risk_exposures/child_growth_failure/wasting/wasting_state_exposure/index.rst
Includes both: 
- Subnational approach details 
- Updates to the MAM subcategory data and RR's with new links to csv's and notebooks + an explanation
=> Updating the MAM subcategory exposure info

docs/source/model_design/programming_vivarium/debugging/index.rst
Page with some info on model debugging. Let me know if the example is unclear. I considered adding photos but didn't want to overcomplicate. If pics would be helpful though lemme know and I can try and force an error to add photos of a stack trace, etc. 
Also including the engineers here if they have other thoughts to include or edit.
=> Writing debugging page

docs/source/model_design/general_reference_material/bliss/sex_gender/index.rst
Just realized I accidentally removed the Table of Contents from this page when I reorganized the BLISS pages!
=> Add TOC back into sex/gender guide

docs/source/models/intervention_models/lipid_based_nutrient_supplements/index.rst
- Add the latest file for effect generation here 
- Add the current status and file for targeting
=> Updating docs from SQ-LNS work

docs/source/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.rst
Corresponding PR with the notebook creation/analysis: https://github.com/ihmeuw/vivarium_research_nutrition_optimization/pull/171
=> Model 14.1 V&V write-up

docs/source/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.rst
- Nigeria and Pakistan look good! 
- Ethiopia does not.
=> Model 14.1 V&V Part 2

docs/source/model_design/vivarium_model_components/risk_factors/risk_effects/index.rst
This addresses the PR comment from #1504. @aflaxman, if you approve I think we can merge this, and then merge #1504.
=> Address PR comments in non-log-linear PR

docs/source/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.rst
Other, related PR: https://github.com/ihmeuw/vivarium_research_nutrition_optimization/pull/178
=> Model 15 V&V

docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst
This PR provides placeholder values of a few data inputs for our intrapartum concept model decision tree: 
- Incidence of ectopic pregnancies, abortion, or miscarriage (using GBD; confirmed that this is incidence across total population) 
- % of simulants attending each facility type (we will do a more in-depth DHS analysis for the country-specific numbers, but for now using a study that used Ethiopia DHS) 
- % of each delivery facility type that has c-section capabilities (using Ethiopia EmONC Assessment; we will need to do more data seeking to find similar data sources for Pakistan and Nigeria) 
There are more data values to update in this table, but in order to keep this PR from getting too big, I will make those updates in a separate PR!
=> Update intrapartum concept model

docs/source/models/causes/maternal_disorders/gbd_2021_mncnh/maternal_sepsis.rst
Add scope and summary of Vivarium modeling strategy for maternal sepsis.
=> MNCNH: Maternal sepsis scope and Vivarium strategy

docs/source/models/causes/maternal_disorders/gbd_2021_mncnh/maternal_sepsis.rst
Adds table of data sources for maternal sepsis, with descriptions of how to compute the incidence risk and case fatality rate needed for the model.
=> MNCNH: Maternal sepsis data table

docs/source/models/causes/maternal_disorders/gbd_2021_mncnh/maternal_sepsis.rst
Add GBD cause hierarchy, restrictions, and descriptions of sequelae for maternal sepsis and other maternal infections.
=> MNCNH: Maternal sepsis cause hierarchy & restrictions

docs/source/model_design/vivarium_model_components/risk_factors/residual_confounding/index.rst, docs/source/model_design/vivarium_model_components/risk_factors/risk_effects/index.rst, docs/source/model_design/vivarium_overview/vivarium_versus_other_model_types/index.rst
Only the ones we moved from backlog yesterday. I suspect this will be the start of a longer project adding links between tickets and to-dos!
=> Adding backlog ticket links to to-dos

docs/source/models/causes/maternal_disorders/gbd_2021_mncnh/index.rst
Create headers for sections describing how model multiple maternal disorders subcauses in the same simulation. This branch will be the base for two more PRs filling in the two subsections.
=> MNCNH: Add section headers for modeling multiple maternal disorders together

docs/source/models/causes/maternal_disorders/gbd_2021_mncnh/index.rst
Jira ticket: [SSCI-2039](https://jira.ihme.washington.edu/browse/SSCI-2039)
Add intro to section on modeling multiple maternal disorders subcauses together, and fill in section describing ordering of the subcauses.
Sequel to https://github.com/ihmeuw/vivarium_research/pull/1556
=> MNCNH: Maternal disorders ordering

docs/source/models/causes/maternal_disorders/gbd_2021_mncnh/maternal_hemorrhage.rst
Checked [GBDcompare](https://vizhub.healthdata.org/gbd-compare/#) and confirmed YLDs are zero for age groups over 55.
=> Update maternal hemorrhage page with cause hierarchy and sequelae and restrictions tables

docs/source/models/causes/maternal_disorders/gbd_2021_mncnh/maternal_hemorrhage.rst, docs/source/models/causes/maternal_disorders/gbd_2021_mncnh/obstructed_labor.rst
Same validation criteria as sepsis and OL
=> Add validation criteria for maternal hemorrhage

docs/source/model_design/programming_vivarium/index.rst
(And make package order match cookiecutter script from viavrium_research_template)
This will make it easier to use the cookiecutter script, although I also have a better solution on the script side...
=> ENH: add info to programming_vivarium page

README.rst, docs/source/onboarding_resources/contributing/index.rst
=> Add quickstart to readme

docs/source/conf.py, docs/source/models/intervention_models/neonatal/cpap_intervention.rst
Suggestion of how to address https://github.com/ihmeuw/vivarium_research/pull/1590#issuecomment-2640640518
=> Explain use of risk components for CPAP intervention more explicitly

docs/source/models/intervention_models/neonatal/cpap_intervention.rst
Suggestion for https://github.com/ihmeuw/vivarium_research/pull/1598#discussion_r1976125276
=> Add alternative PAF derivation to CPAP page

docs/source/models/causes/neonatal/preterm_birth.rst
Please let me know if there are any questions/edits.
I also changed the integral to mean RR because that was more straightforward to me, but let me know if anyone feels strongly about changing it back.
=> Updates to preterm cause model

docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst
I didn't add c-sections because I believe that's wave 2 - not sure if I should add wave 2 interventions too. Also I'm not sure this is the order we're planning on implementing these in.
=> Add maternal intervention models to Model Run Requests table

docs/source/models/concept_models/vivarium_mncnh_portfolio/ai_ultrasound_module/module_document.rst, docs/source/models/concept_models/vivarium_mncnh_portfolio/antenatal_care_module/module_document.rst, docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst, docs/source/models/concept_models/vivarium_mncnh_portfolio/facility_choice_module/module_document.rst, docs/source/models/concept_models/vivarium_mncnh_portfolio/initial_attributes_module/module_document.rst, docs/source/models/concept_models/vivarium_mncnh_portfolio/intrapartum_interventions/module_document.rst, docs/source/models/concept_models/vivarium_mncnh_portfolio/maternal_disorders_module/module_document.rst, docs/source/models/concept_models/vivarium_mncnh_portfolio/module_template/module_document.rst, docs/source/models/concept_models/vivarium_mncnh_portfolio/neonatal_interventions/module_document.rst, docs/source/models/concept_models/vivarium_mncnh_portfolio/neonatal_mortality_module/module_document.rst, docs/source/models/concept_models/vivarium_mncnh_portfolio/pregnancy_module/module_document.rst
So far I have not moved any content! I just made the new module pages from a template and created tables that link to them. I will move content in subsequent PRs so that we can more easily track changes in git to make sure all appropriate information in preserved.
=> Create module tables and subpages

docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst
=> Update V&V tracker with probiotics run

docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst
Not sure if I'm using this table in the right way to document what we'd like in the new births observer, or maybe this info goes somewhere else.
I'm trying to communicate that we'd like birth counts stratified by: 
- delivery facility type
- pregnancy outcome
- child sex
- scenario
- input draw
=> Update documentation for births observer

docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst
This PR updates both the model run requests table and the V&V tracker table to include all prior runs. I added a 'File path' column to the model run requests table and retrospectively filled in those of past runs.
=> MNCNH V&V notebook clean-up

docs/source/model_design/vivarium_features/other_causes_ylds/index.rst
Small update to this, which I ran up against/got curious about as I worked on the iron-responsiveness adjustment in the LSFF model.
I've shared the ticket with everyone tagged here.
=> Correct and update note about COMO restrictions

docs/source/models/templates/concept_model_template.rst
It sounds like this has been a bit of a pain point, so I thought I would outline some "best practices" for using the V&V template tables as I envision them being used. I think we can probably review this outside of a documentation session, but if discussion gets lengthy let's plan to table it until we have time to discuss as a group.
=> VV tracking best practices proposal

docs/source/models/intervention_models/neonatal/probiotics_intervention.rst
This PR updates our neonatal probiotics documentation so that only preterm early neonates are eligible for receiving probiotics. I made a very simple diagram of who's eligible. Please let me know if I should document this differently!
=> Update effective coverage of probiotics 

docs/source/model_design/general_reference_material/bliss/race_ethnicity/index.rst
I added this in a similar spot to where it is for the sex/gender guide, but would love feedback if this feels right. Otherwise this is largely the same as what was seen in the word doc.
=> Adding race/ethnicity glossary to BLISS 

docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst
I wanted to add this info to make sure we will be all set for V&V! We need to add a new scenario to make sure we can do V&V as two of our locations do not have baseline coverage. Let me know if we want to structure this scenario differently!
=> Azithromycin model run request

docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst
We had discussed this in an MNCNH RT meeting a little while back -- updating outstanding todo note in accordance with that conversation.
=> MNCNH model specification notes

docs/source/model_design/general_reference_material/bliss/race_ethnicity/index.rst
I adapted our 'What this is vs. what this isn't' table and our guiding principles from the sex and gender guide for the race and ethnicity guide. I didn't change a lot and I tried to keep it very high-level, so hopefully it doesn't feel too redundant with later sections in the guide, but would appreciate folks' feedback on that!
=> Add Overview/Guiding principles to BLISS race and ethnicity guide

docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst, docs/source/models/intervention_models/neonatal/antibiotics_intervention.rst
All of the studies I looked at are saved here in case anyone would like to take a look: https://uwnetid.sharepoint.com/sites/ihme_simulation_science_team/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Fihme%5Fsimulation%5Fscience%5Fteam%2FShared%20Documents%2FResearch%2FBMGF%5FMNCH%2FMNCNH%20portfolio%20products%2F03%5Fliterature%2Fantibiotics&viewid=e7a7188c%2Db8d6%2D464c%2D9495%2De503c9cde40d
Happy to discuss when we are all back in on Monday!
=> Research summary and todo notes to update modeling strategy

docs/source/models/causes/neonatal/index.rst, docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst
Abie wanted to do a simple first pass of this strategy before moving forward with more details, so that's what we will do for model 8.1 and then if it looks promising I will update with more specific details for model 8.1.1
=> First pass LBWSG RR cap docs and model 8.1 request

docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst
Jira ticket: [SSCI-2326](https://jira.ihme.washington.edu/browse/SSCI-2326)
Sequel to #1692
Update MNCNH concept model to make language consistent with facility choice docs. Specifically, I edited the module tables for the pregnancy component and intrapartum component.
When I changed "Delivery facility propensity" to  "IFD propensity" in the module tables, I thought I should define "IFD" somewhere. Then I realized that there were a ton of abbreviations throughout the page with no definitions, so I made an abbreviations table. **Please double check to make sure I have the correct definitions for all the abbreviations**, and let me know if I missed any!
=> MNCNH: Concept model abbreviations and language for facility choice

docs/source/models/concept_models/vivarium_alzheimers/concept_model.rst
Please note I changed the V&V criteria for model 2.2. Would appreciate confirming that we are good with this!
=> Model 2.1 V&V and model 2.2 request

docs/source/models/concept_models/vivarium_alzheimers/concept_model.rst
I snuck a few things in here: 
- Model 2.2 V&V (we did it!) 
- Updates to model 2 and 3 V&V to match what I did and change model 3 V&V to not be ACMR but rather total mortality
- Added a V&V issue tracking table
=> Model 2.2 V&V + Some table updates

docs/source/models/concept_models/vivarium_alzheimers/concept_model.rst, docs/source/models/intervention_models/alzheimers/testing_diagnosis.rst
Add observer and v&v and clarify sections related to engineering questions
=> Model 6 (formerly 7; testing intervention) PR #2
