docs/source/models/gbd2017/causes/index.rst

The table of contents was looking very cluttered because it was showing all the section headings; this changes it to only show the title of each cause model document.

Change TOC depth to 1 for GBD 2017 causes

---

docs/source/models/gbd2017/causes/index.rst
docs/source/models/gbd2017/causes/neonatal_encephalopathy/index.rst
docs/source/models/gbd2017/causes/neonatal_jaundice/index.rst
docs/source/models/gbd2017/causes/neonatal_other/index.rst
docs/source/models/gbd2017/causes/neonatal_sepsis/index.rst
docs/source/models/gbd2017/concept_models/vivarium_conic_lsff/concept_model.rst
docs/source/models/gbd2017/risk_attributable_causes/index.rst
docs/source/models/gbd2017/risk_attributable_causes/iron_deficiency/index.rst
docs/source/models/gbd2017/risk_attributable_causes/vitamin_a_deficiency/index.rst
docs/source/models/gbd2017/risk_effects/index.rst

I added stubs for the neonatal causes and the PAF-of-1 vitamin A and iron deficiency causes, and I fixed a copy/paste typo in the "Risk Outcome Relationship Models" stub. I started a new directory structure where each cause goes in its own subfolder to keep the related files together, and I modified the appropriate index files accordingly.

Add stubs for causes in LSFF model

---

docs/source/models/cause.rst

This PR is to update the existing description of prevalence as a data source for cause model initialization to clarify that GBD prevalence estimates are estimates of point prevalence at the midpoint of a given year and to discuss assumptions about how we use this point prevalence estimate across full simulation year(s). 
Let me know if you have any feedback! Thanks

clarify that gbd point prevalence represents year midpoint

---

docs/source/models/gbd2017/causes/cause_model_template.rst

Here's a new version that incorporates some suggestions from the previous PR https://github.com/ihmeuw/vivarium_research/pull/91 :
1. Remove "Disease Description" section, and just put the description at the top level of the document.
2. Remove the cause name from the GBD Modeling section title.
3. Move the restrictions table into the GBD Modeling section.
4. Remove the section "Model Assumptions and Limitations," and replace it with a section called "Vivarium Modeling Strategy," with two subsections, "Scope," and "Assumptions and Limitations." This new section comes right before the "Cause Model Diagram" section.
I have copied relevant comments from several pull requests into the template todo boxes, so we can see all the discussion relevant to section structure in one place.
Post …

Cause Model Template: Change section names and structure; add GBD Restrictions table

---

docs/source/models/gbd2017/causes/cause_model_template.rst

Switching gears temporarily from section structure, here are some proposed templates for the YLD/CoD appendix references. There are several issues where it would be good to get feedback:
- Does the formatting look good?
- Is it clear what is being referenced? I included a link to the appendix, plus the full citation for the capstone paper. Does this make sense? Is there a better way to cite the appendices?
- I put in question marks (???-???) as a place holder to fill in the correct pages in the appendices. Is this useful, or will it be annoying to fill in the correct page numbers in each document?
- What do people think of the "Tip" directive I put after the citations? Is it helpful? Should it be an "Important" directive instead, like the one at the beginning of the document?
- I proposed …

Cause Model Template: add references to YLD & CoD appendices

---

docs/source/models/cause.rst
docs/source/models/gbd2017/causes/causes.rst

I made some minor changes to 2 files to get rid of warnings when building html with Sphinx:
In `docs/source/models/cause.rst`:
- Fix broken links to "Duration" and "Progression" sections in the Data Definitions table
In `docs/source/models/gbd2017/causes/causes.rst`
- Change the document's internal hyperlink target to `2017_cause_models_gbd` because it conflicted with the one in `docs/source/models/gbd2017/causes/index.rst`
- Fix title underlines that were too short
- Minor edits in first paragraph (fix typo plus clarify definition of cause in first sentence)
All the other changes shown by git appear to be removal of extraneous whitespace, which must have happened automatically in my text editor.

Fix syntax in "Modeling Causes" and "Cause Models in GBD"

---

docs/source/models/gbd2017/causes/cause_model_template.rst

Here is a slightly revised section structure based on comments from @beatrixkh and @collijk in PR https://github.com/ihmeuw/vivarium_research/pull/93 . Namely:
1. To make it clearer that this document is itself a template rather than a document about what template to use, I added a subtitle that will become the title for each cause model document, and instructed the reader to *delete* the document's current title, "Cause Model Template," when they start editing.
2. I reorganized the document into 3 main sections, and I indicated that there should be an overview at the beginning of each section that has subsections. See the first "template todo" in the document for details.

Cause model template: Revise section structure based on PR 93 comments

---

docs/source/gbd2017_models/risks/risk_exposure_template.rst

I accidentally merged the risks_stub branch without incorporating your comments. They've been incorporated here.
I've also expanded the risk exposure template to have more detail. I didn't do it in @NathanielBlairStahn 's to-do form; I found it somewhat confusing to discern which todos were for the template page, vs for the specific cause page---so wanted to check out this version. happy to convert over if we prefer the todo format!

Risk exposure template

---

docs/source/gbd2017_models/concept_models/vivarium_conic_lsff/concept_model.rst

Once again, my editor deleted a bunch of whitespace, so git shows lots of extraneous changes. To see only the substantive changes, click the gear icon at the top and select the box that says "Hide whitespace changes":
The new content is primarily in the section "Stratifying Exposure Variables by Baseline Intervention Coverage."

LSFF: Write intro to stratifying on baseline coverage

---

docs/source/gbd2017_models/concept_models/vivarium_conic_lsff/concept_model.rst

- Fixed description of birthweight shift to use mean for downshift
- Clarified that flour consumption is only needed if mother is fortified
- Changed duration of fortification to account for children not eating solids before 6 months
- Fixed hemoglobin shift to account for iron-responsive vs. non-responsive anemias
- Added a description of the iron algorithm summary section

LSFF: Iron algorithm updates

---

docs/source/model_design/risk_factors.rst

Nathaniel, you suggested this for the PAF equations section and I accidentally remade the labels without re-doing the references to the labels in the last PR.
This now links all references to the three PAF equations to the equations themselves.

Replacing numbered references to equations with links to equations

---

docs/source/concept_models/vivarium_conic_lsff/concept_model.rst

I updated the "Summary of Iron Intervention Algorithm" section as follows:
- Incorporated corrected/clearer pesudocode for the Hb shift from the section "Determining Whether A Simulant is Affected - Iron > Hemoglobin Level," and added comments to both pseudocode blocks to better describe what is happening.
- Corrected a bug in the calculation of coverage duration in both pseudocode blocks:
```time_since_fortified_i(t) = min(t - time_covered_i, t - age_i(t) + 0.5)```
became
```time_since_fortified_i(t) = min(t - time_covered_i, age_i(t) - 0.5)```
because `age_i(t) - 0.5` is the time since the simulant turned 6 months old (which is what we want), vs. `t - age_i(t) + 0.5`, which is the time at which the simulant turned 6 months old (which is **not** what we want).
- Removed the code dealing …

Lsff update iron intervention summary

---

docs/source/gbd2019_models/causes/afib/index.rst

I accidently merged the last PR before making these changes, so I created a new PR.
I chose to use "A" instead of "P" or "C" for the prevalent state to match the cause model diagram, but noticed that Nikki chose to go with "C", and am happy to change it to "C" and update the diagram if people prefer them to match.

Fixed the A/P state discrepency.

---

docs/source/gbd2019_models/risk_effects/risk_effects_template.rst

This PR corrects some errors in the instructions for the Risk Effects Model Template, and updates the citation of the 2017 risk appendix to the 2019 risk appendix. I also reformatted the initial two `important` and `todo` directives into a single `todo` directive -- let me know if the new version seems clear.

Risk effects template cleanup

---

docs/source/gbd2019_models/causes/lower_respiratory_infections/index.rst

I couldn't find info on this in the GBD 2019 appendix, and reading our documentation for GBD 2017 LRI, i couldn't tell if the "we" referred to we of sim science, or was referring to "we the gbd modelers". need help with clarification!

assumptions / limitations: GBD 2019 LRI

---

docs/source/gbd2019_models/risk_effects/low_birthweight_short_gestation/index.rst

Here's the start of the LBWSG Risk Effects document for GBD 2019. I have only worked on the "GBD 2019 Modeling Strategy" section, **not** the "Vivarium Modeling Strategy" section (all that content is from the template). Specifically:
* I added a citation to the GBD 2019 risk appendix
* I copied in a bunch of text (lightly edited) from the risk appendix to describe the GBD modeling strategy
* I made a table of the affected causes
* I made a table of the age/sex/outcome restrictions in GBD, with a note about how the PAF-of-1 cause Neonatal Preterm Birth is different

LBWSG Risk Effects - GBD 2019 Modeling Section

---

docs/source/gbd2019_models/risk_effects/low_birthweight_short_gestation/index.rst

Here's a description of the method I used to interpolate the Low Birthweight & Short Gestation relative risks for the large-scale food fortification project.
The section got kind of long because I was trying to describe the procedure in enough detail to reproduce what I did.  If it's too much to digest in one PR, let me know and I can try to split it up.

LBWSG relative risk interpolation

---

docs/source/gbd2019_models/risk_effects/risk_effects_template.rst

My assumption in PR https://github.com/ihmeuw/vivarium_research/pull/482 was wrong -- we have **not** done anything to fix the global citation problem discussed in PR https://github.com/ihmeuw/vivarium_research/pull/99.
Therefore I am reverting the citation in the GBD 2019 Risk Effects Model Template to the original version with the page name appended, and adding back in the instructions to do the same thing for pages based on the template.
For reference, here's an example of the "global citation problem":
* The [CDC] citations in the first paragraph of the [2017 Measles document](https://vivarium-research.readthedocs.io/en/latest/gbd2017_models/causes/measles/index.html) and the [2019 Measles document](https://vivarium-research.readthedocs.io/en/latest/gbd2019_models/causes/measles/index. …

Make citation in 2019 risk effects template unique to the page

---

docs/source/gbd2019_models/risk_exposures/wasting_state_exposure/index.rst

Updated wasting exposure page to include
- new code with which we solve transition rates in terms of dur_cat3 and i3
- tables with new transition rates
Todo: 
- fix the tables (they need to wrap)
- should those transition rates be included anywhere else in the page?
- would it be nice to have a visualization of the matrix equation we're solving? it's implicit in the equations but not included, as of now
Todo later:
- include a death state and update all equations. right now we assume too many people are remitting who should be dying.

Wasting transitions equations update

---

docs/source/model_design/correlated_risks/index.rst

Fixes some title underlines that were too short, and replaces the unknown `:raw-latex:` role with a `.. math::` directive. Also, my text editor removed a bunch of whitespace.

Fix syntax errors in `correlated_risks/index.rst`

---

docs/source/concept_models/vivarium_ciff_sam/concept_model.rst

There's some superfluous whitespace changes, but the main thing is I added subsections under the concept model diagram that link out to the pages for the model components.
Note: I left out vitamin A deficiency because @Ninicorn said she's going to remove that.

CIFF SAM Concept Model: Add links to pages for model components

---

docs/source/gbd2017_models/risk_exposure/low_birthweight_short_gestation/index.rst
docs/source/gbd2019_models/risk_effects/low_birthweight_short_gestation/index.rst

This describes a mini simulation we can run to validate the application of the relative risks.
I couldn't remember the details of why we decided to apply the RRs only to affected causes instead of all-cause mortality, so I put a question about it in here that should be addressed at some point.

GBD 2019 LBWSG Risk Effects: Add some validation strategies

---

docs/source/concept_models/vivarium_ciff_sam/concept_model.rst
docs/source/gbd2019_models/risk_effects/low_birthweight_short_gestation/index.rst

Sequel to https://github.com/ihmeuw/vivarium_research/pull/576
Add links to the LBWSG 2019 risk exposure page from the CIFF acute malnutrition concept model and from the LBWSG 2019 risk exposure pages.

LBWSG 2019 exposure: Add links from other pages

---

docs/source/gbd2019_models/risk_exposures/low_birthweight_short_gestation/index.rst

Sequel to https://github.com/ihmeuw/vivarium_research/pull/576
Describe strategy for converting LBWSG categorical exposure distribution to a continuous exposure distribution, with links to sample code.

LBWSG 2019 exposure: Start Vivarium modeling section

---

requirements.txt

`sphinx-rtd-theme` updated to 1.0 and seems to have some issues related to custom css themes.  See: https://github.com/readthedocs/sphinx_rtd_theme/issues/1236.  Pinning the version for now, which should fix things.

Roll back sphinx-rtd-theme

---

docs/source/intervention_models/lipid_based_nutrient_supplements/index.rst
docs/source/intervention_models/wasting_treatment/index.rst
docs/source/model_design/concept_model/statistical_distributions_uncertainty/index.rst

**Tip:** Hide whitespace changes to see my real changes (see screenshot below), since Atom automatically deletes whitespace when I save files.
I added a section to the "Statistical Distributions of Uncertainy" page in the Vivarium Model Design section to describe how to fit a lognormal distribution to a median and confidence interval, and I added links to the algorithm from the SQLNS and Wasting Treatment Intervention pages for the CIFF SAM project.
I believe @rmudambi already implemented these changes in model 4 based on Slack discussions, but this PR makes it official.

Lognormal parameter uncertainty for SQLNS effect sizes & SAM K parameter

---

docs/source/intervention_models/wasting_treatment/index.rst

This PR finalizes our previously-temporary fix of excluding infants under six months of age from the wasting treatment model and notes a potential sensitivity analysis of making assumptions regarding the efficacy of wasting treatment among infants as an additional scenario in the future.

Exclude infants less than six months from wasting treatment model

---

docs/source/concept_models/vivarium_ciff_sam/concept_model.rst
docs/source/concept_models/vivarium_ciff_sam/x_factor_risk_effect.csv
docs/source/gbd2019_models/risk_effects/x_factor/index.rst
docs/source/gbd2019_models/risk_effects/x_factor/x_factor_risk_effect.csv
docs/source/gbd2019_models/risk_exposures/x_factor/index.rst
docs/source/gbd2019_models/risk_risk_correlation/maternal_bmi_x_factor/index.rst

I made individual pages for the x-factor risk exposure and risk effects documentation instead of having them in the concept model because I think it was getting cluttered. This PR doesn't add/change any information, just moves it around.

make risk exposure and risk effects page for x-factor

---

docs/source/concept_models/vivarium_ciff_sam/concept_model.rst
docs/source/gbd2020_models/risk_attributable_causes/wasting/index.rst
docs/source/intervention_models/wasting_treatment/index.rst

These changes should not be implemented until after the calibration changes are made and reviewed
The coverage parameter (C) was split into C_MAM and C_SAM. Intervention scenario targets were updated. 
A strategy to account for the difference between coverage defined as percent of population vs. percent of population in need will need to be implemented but is not yet reflected in this PR.

CIFF wasting treatment coverage updates

---

docs/source/concept_models/vivarium_ciff_sam/concept_model.rst
docs/source/gbd2020_models/risk_attributable_causes/wasting/index.rst
docs/source/intervention_models/insecticide_treated_nets/index.rst
docs/source/intervention_models/lipid_based_nutrient_supplements/index.rst
docs/source/intervention_models/maternal_malaria_prevention_therapy/index.rst
docs/source/intervention_models/maternal_supplementation/index.rst
docs/source/intervention_models/wasting_treatment/index.rst

This PR does not change any modeling strategy or data values, but is intended to clarify scenario-specific values related to intervention coverage and avoid listing parameter values in multiple places in the documentation as requested by Rajan (a few additional PRs will be coming to do the same thing on other pages).

CIFF intervention coverage parameter docs single source of truth

---

docs/source/gbd2020_models/risk_attributable_causes/wasting/index.rst

update wasting exposure document to link to intervention document so parameters values are not defined in multiple places
also, add in treatment efficacy parameters to wasting transition equations, which is what is being done in the code (as confirmed by Rajan), but was not reflected in the documentation.
this PR does not change any modeling strategy or data values.

Wasting parameter single source of truth and addition of efficacy parameter

---

docs/source/gbd2019_models/risk_effects/low_birthweight_short_gestation/index.rst

Adds a section to the GBD 2019 Low Birthweight and Short Gestation risk effects documentation to explain how to compute a PAF for the interpolated relative risks using Monte Carlo integration.

Risk effects: LBWSG 2019 PAF

---

docs/source/concept_models/vivarium_ciff_sam/concept_model.rst

We don't need observers for the burn-in period if that would be beneficial for run time/other constraints, but it would also be fine to have observers during that period, too.

CIFF burn-in period request

---

docs/source/gbd2019_models/risk_effects/diarrheal_diseases/index.rst

This was an error in the documentation that was inconsistent with the equations I was using in my calculation of the diarrheal diseases risk effects external to this document. The inconsistency was identified by Rajan and he is planning on implementing it as shown in this updated PR.

Vicious cycle remission rate equations fix

---

docs/source/other_models/pregnancy/index.rst

I accidentally recorded the covariate ID for live births by sex instead of the still birth ratio. I'd be surprised if this was included in the model since the correct ID for SBR is included in other places and the SBR is less than 1 and live births by sex is in the many thousands, so I think we would have noticed, but just FYI!

Pregnancy model fix wrong covariate ID

---

docs/source/concept_models/vivarium_iv_iron/maternal_model/concept_model.rst

Matt and Jim caught an error in my plots that I was comparing maternal disorders burden to maternal hemorrhage burden, erroneously making it look like we were overestimating maternal disorders burden. Here are the updated conclusions now that that's been fixed

Maternal disorders cause model validation updates

---

docs/source/concept_models/vivarium_iv_iron/maternal_model/concept_model.rst

this is the same typo that I fixed in one other place already, again, I don't think that it was incorporated into vivarium

fix error in stillbirth ratio covariate ID

---

docs/source/concept_models/vivarium_iv_iron/child_model/concept_model.rst
docs/source/gbd2019_models/risk_effects/maternal_hemorrhage/index.rst

It doesn't look like there are any software bugs in the child sim, but a few things to note:
- There are LRI and diarrheal diseases research validation issues to sort out. These mainly affect the neonatal age groups so we considered them ok for CIFF, but it will be more impactful for this project so we should try to get these resolved.
- We're using GBD 2019 rather than 2020 age groups, so we'll have to decide if we think it's worth updating this in order to use the GBD 2020 child growth failure risk factors. I think it would be acceptable to use 2019 exposures given the following:
- From Ryan Fitzgerald: `Hi all, I'm Ryan, I model CGF and LBWSG exposure on GBD. I have been messaging with Nicole about your project and specifically about how the relative risks changed from GBD2019 - …

iv iron child sim validation

---

docs/source/other_models/pregnancy/index.rst

this is a new feature request that we will need to create a ticket for
Software engineers let me know if the goal here isn't clear! We're hoping that this will be a simple change in the artifact age_start and age_end values that vivarium should be able to handle automatically.

document age shifting of pregnancy parameters

---

docs/source/concept_models/vivarium_iv_iron/child_model/concept_model.rst

I had a comment about underestimating the PEM CSMR, but it was really because I was misunderstanding the definition of the severity-specific PEM CSMR in the artifact, which was actually for all PEM not severity-specific. Plots are now updated to reflect that here: https://github.com/ihmeuw/vivarium_research_iv_iron/blob/main/validation/child/model_2/model_2.1.1_cause_model_validation.ipynb

update child v and v table

---

docs/source/concept_models/vivarium_iv_iron/maternal_model/concept_model.rst

Note that the timestep for the maternal simulation is specified as 2 weeks here, but I think we have been running with 1 week. We can should be able to double it for future runs.
Also, if the updated seed specifications do not look as expected to the SWEs, please let me know!

IV iron simulation parameter update

---

docs/source/concept_models/vivarium_ciff_sam_2/concept_model.rst

I realized we could get away with a shorter run time here, so updating this parameter to decrease our cluster load. Tagging as SE required to make sure this update is caught.

Wasting model baseline scenario run time update

---

docs/source/concept_models/vivarium_census_synthdata/concept_model.rst

It is not correct to treat GQ person weights as equivalent to household weights, as they have different units.

Correct issue with GQ person weights in migration

---

docs/source/concept_models/vivarium_census_synthdata/concept_model.rst

I realized that the existing documentation for what I was calling "residential address" (the place where the living quarters are physically located, as opposed to "mailing address") would not work for GQ -- in particular, it used PUMA, which isn't a thing that can be determined for a GQ "household."
Because we use "residential" throughout the concept model to specifically mean the **opposite** of GQ, I've proposed changing our terminology to "physical" vs mailing address.

Correct physical address to work in the GQ case

---

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst

Turns out, these deeply nested headings don't really render in ReadTheDocs (they do on my local Sphinx). Don't want to mess with this too much, but making them italic at least makes it easier to tell what is going on.
Current rendering:

Make PRL subheadings italic

---

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst

To make the noise functions work, we need to set the DOB in all observers to be a standard string. Selecting MM/DD/YYYY here.

Defining the format for DOB

---

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst

I got mixed up here, which became clear at implementation time when values outside the domain of the function were causing errors. Thanks @albrja for catching!

Correct probit to standard normal CDF

---

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst

@albrja pointed this out -- I documented it in a way that presumed the implementation, and I was wrong about how it was implemented.

Replace use of "parent_ids" with description

---

README.rst

Edit instructions in `README.rst` to suggest cloning the repo using `https` rather than `ssh`, as that's GitHub's recommended method and doesn't require the user to set up an SSH key.

Switch from ssh to https in contributing instructions

---

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst

Continuing the cleanup of the PRL concept model document started in #1124. This PR focuses on the "demographics" section and the first component, which is everything we initialize from ACS. I want to separate the guardian part into its own component in the list, but am leaving that for a future PR.

Clean up demographics and ACS-based initialization

---

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst

Just a few spots of undefined behavior I ran into while trying to run the simulation with very small populations. I have already implemented this in https://github.com/ihmeuw/vivarium_census_prl_synth_pop/pull/224 because I do not expect it to be controversial.

Handle edge cases for very small populations

---

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst

It was very annoying trying to find specific sections without having them listed and linked in the contents, so I removed the depth limit in order to display every subsection at the top of the file.

Remove depth from PRL concept model

---

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst

As pointed out by @stevebachmeier, the decennial Census does not record mailing address so there is no PO box in that observer.

Remove decennial census from PO box observers

---

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst

@stevebachmeier pointed out some errors in this column; we're removing it altogether as not needed.

Remove redundant "additional parameters" column

---

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst

Allows specifying the probabilities of each perturbation, and changes the strategy for dealing with negative ages.

Revise age miswriting noise function

---

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst

Noticed while doing this that it does already say this in the right-hand column of the table; but I made this format more consistent.

Nit: consistent format for ZIP in noise table

---

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst

Record a Race/Ethnicity column in the ACS and CPS household surveys. This column is needed to implement row omission noise, and we also want it in the final output of pseudopeople.

Add race/ethnicity to PRL household surveys

---

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst

Make changes in column noise table to match what we're actually recording in each observer:
- Remove age from WIC and SSA datasets
- Remove PO box from Household Surveys and WIC
- Add Race/Ethnicity to Household Surveys

PRL: Clean up column noise table

---

docs/source/model_design/vivarium_model_components/risk_factors/risk_effects/index.rst

This PR creates a Restrictions section on the Risk Effects page, which includes:
- description of what restrictions are
- explanation of the relationship between risk exposure restrictions and risk effect restrictions 
- example risk effect restrictions table (from LBWSG model)

Risk effects restrictions section

---

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst

As discussed:
- The combination of "borrowed" SSN and copy-within-household noise types both happening one after the other leads to some confusing scenarios
- Someone (who actually has an SSN) accidentally using the SSN of someone else in their household on a W2 does not seem like a very likely form of noise anyway
This will need to be reflected in pseudopeople docs as well; those don't exist yet.

Don't copy within household for SSN in W2 dataset

---

docs/source/models/causes/maternal_disorders/gbd_2021/index.rst
docs/source/models/causes/maternal_hemorrhage_incidence/index.rst
docs/source/models/concept_models/vivarium_nutrition_optimization/pregnancies/concept_model.rst
docs/source/models/other_models/pregnancy/gbd_2021_closed_cohort/index.rst

1. Added V&V plans to the next 2models in case I am out when model results come in 
2. Added note that it would be an acceptable limitation for interventions to affect LBWSG exposure only and not pregnancy duration, with a todo note to update docs to whatever ends up being implemented
3. Added removal of background mortality to cause model section, with a todo note to figure out which model version to implement the removal
4. Bolded output stratification requests to make them more visible
5. Clarified the preg_rate parameter in the maternal disorders cause model doc (doesn't change the implementation, just tried to make parameter definition less confusing)

Misc. pregnancy model updates from rt/se

---

docs/source/models/causes/maternal_disorders/gbd_2019/index.rst
docs/source/models/causes/maternal_disorders/gbd_2021/index.rst

Found a small error in our YLD equation for maternal disorders from the IV iron implementation. Updated the equation in the 2021 document (and noted the updated from the prior implementation) and called out that the implemented equation in the 2019 document is incorrect but kept it there for reference.

Maternal disorders YLD equation fix

---

docs/source/models/risk_exposures/child_growth_failure/wasting_state_exposure/index.rst

In addition to the todo notes, this PR also:
- removed some more PEM-specific info that I missed on the first go-round, 
- removed the joint wasting/diarrhea model diagram, 
- simplified redundant info in the data sources table, 
- and made a few copy edits
- updated some 2020s to 2021s

Add to-do notes for anticipated wasting exposure model changes

---

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst

I also removed the 'type of tax form' column because it seemed specific to W2/1099 forms? 
Changes as discussed in 7/13 RT/SE Check-in 
Jira ticket: https://jira.ihme.washington.edu/browse/SSCI-1449

Update concept model to remove employer and income columns from 1040

---

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst

JIRA tickets: [SSCI-1464](https://jira.ihme.washington.edu/browse/SSCI-1464), [SSCI-1395](https://jira.ihme.washington.edu/browse/SSCI-1395)
Makes some changes to the Social Security observer:
- Change middle initial to middle name
- Add an event ID column for comparing noised to unnoised data
- Edit noise table to reflect the change from middle initial to middle name in SSA dataset
The change from middle initial to middle name is based on these [archival NUMIDENT files from NARA](https://aad.archives.gov/aad/series-description.jsp?s=5057).
I haven't yet added these changes to the pseudopeople docs since I don't know whether they'll be included in the yellow release.

PRL: Add middle name and event ID to SSA columns

---

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst

Re-orders some columns in the taxes W2 & 1099 dataset, taxes 1040 dataset, and social security dataset, in order to put ground-truth columns first and to more closely match the order of fields in the corresponding real versions:
- [W2](https://www.irs.gov/pub/irs-pdf/fw2.pdf), [1099-MISC](https://www.irs.gov/pub/irs-pdf/f1099msc.pdf), [1099-NEC](https://www.irs.gov/pub/irs-pdf/f1099nec.pdf)
- [1040](https://www.irs.gov/pub/irs-pdf/f1040.pdf)
- [SSA Numident](https://aad.archives.gov/aad/series-description.jsp?s=5057)
@albrja This can serve as the single source of truth for how we want to reorder the columns. Note that I moved the "Event ID" column in the SSA dataset, which doesn't exist yet (it's slated for orange release), so you can ignore that.
- Engineering JIRA ticket: …

PRL: Reorder dataset columns

---

docs/source/models/causes/malaria/index.rst

In Model 3 of the nutrition optimization child model, malaria prevalence and CSMR was lower than expected. We believe this is due to a mismatch between GBD data sources, as is present in other cause models such as LRIs. Therefore, the prevalence is changed to be based on incidence and duration instead of GBD data.

Updating malaria prevalence to be based on incidence and duration

---

.readthedocs.yml

Deprecation: https://blog.readthedocs.com/use-build-os-config/
Docs: https://docs.readthedocs.io/en/stable/config-file/v2.html

Use `build.os` for RTD

---

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst

JIRA ticket: [SSCI-1540](https://jira.ihme.washington.edu/browse/SSCI-1540)
Update PRL concept model to allow applying "omit a row" (simple omission) noise to census and surveys. Previously, we only allowed "do not respond" (targeted omission) noise for these, but there's no reason not to allow both.
I also documented the default row probabilities for "omit a row" noise, and I took the opportunity to change the requested default value for WIC from 0.0% to 0.5% (same as what we have for W2/1099), since it seems plausible that WIC could have some missing records. If anyone has a different preference for the default WIC value (or any of the other default values), let me know.
(Note that there are some extraneous whitespace changes that you may want to hide.)

PRL: Update omit row noise

---

docs/source/model_design/general_reference_material/bliss/index.rst

This PR address the following two tickets:
- Introduce target audience of document: https://jira.ihme.washington.edu/browse/SSCI-1594
- And add a table of contents https://jira.ihme.washington.edu/browse/SSCI-1593
There were a couple of points in the description of the second ticket that I am not sure I have met, but figured I would add in the general default table of contents to start! Specifically, there was a link to this resource that I am not necessarily sure how to incorporate and maybe others have ideas to follow-up with (https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style#Retaining_existing_styles). Further, RST automatically links back to the TOC if you click on an individual header in the body of the document, so I don't think we need to make separate links!
Thanks and let …

Add table of contents and audience intro to BLISS page

---

docs/source/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.rst

My initial V&V check on this was not scenario-specific which led to the wrong conclusion -- updated now : )

Update to model 11.1 V&V summary

---

docs/source/models/concept_models/vivarium_nutrition_optimization/pregnancies/concept_model.rst

@hussain-jafari I think we had a miscommunication in what scenarios we wanted for the pregnancy production runs. I am only seeing scenarios baseline, 0, 1, 2 in the results you sent. We want to keep the targeted BEP scenarios #3 and #4 for wave II, though (we just removed what used to be the "universal" BEP scenario). However, it worked out because I would like to make a change to scenario #3 before we run anyway. Let me know if you have any questions.

Update targeted BEP/IFA scenario cov

---

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst

I missed Zeb's comment suggesting we add this justification of the 2% to the concept model before I merged my last PR - my apologies!

Add reasoning behind default parameter update to concept model (for guardian-based duplication)

---

docs/source/models/concept_models/vivarium_nutrition_optimization/concept_model.rst

Realized that this link hadn't been added in forever so put the latest. I used permalinks which means that even if the emulator is edited in the other open PR, the link will still work as long it has the same name. 
Here is the PR for this emulator version: https://github.com/ihmeuw/vivarium_research_nutrition_optimization/pull/132

Adding newest, cleaned emulator version

---

docs/source/models/concept_models/vivarium_census_synthdata/concept_model.rst

JIRA ticket: [SSCI-1677](https://jira.ihme.washington.edu/browse/SSCI-1677)
Add a warning block noting that we tried sorting rows of the census by year and household ID, but reverted the change because it was too slow, so duplicates are currently appended to the end of each shard.

psp: Add warning about sorting census rows

---

docs/source/model_design/index.rst
docs/source/model_design/programming_vivarium/archiving_models/index.rst
docs/source/model_design/programming_vivarium/artifact_building/index.rst
docs/source/model_design/programming_vivarium/index.rst
docs/source/model_design/programming_vivarium/overview_engineering_files/index.rst
docs/source/model_design/programming_vivarium/running_simulations/index.rst

Hey, couple of notes about this PR: 
1. Adding a new folder and pages for engineering tasks. I think we might well add new pages to this as time goes on, but this is a starting point. 
2. I don't love the name "Vivarium engineering for research team members" if anyone has a better suggestion! 
3. I am also deleting this page: https://vivarium-research.readthedocs.io/en/latest/model_design/vivarium_overview/vivarium_software/index.html (GitHub logged this as renamed and modified rather than deleting and creating a new page). I have added links on the relevant pages in the to-do to integrate, and pasted some of the general paths onto the new, main page. Two pages are getting deleted: Simulations in an interactive setting (I felt like we have a good page for this already) and pulling data …

Adding folder for engineering type tasks and to-do pages

---

docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst

This PR updates the numbers for baseline coverage of standard ultrasounds in our 3 countries of interest. Unfortunately, I was unable to find data for ultrasound use in Pakistan, so here I'm using values from India's 2016 DHS, which I'm not sure is valid (but they do have very similar ANC utilization rates in GBD)! 
Links to the literature:  
- Ethiopia ultrasound rate: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8905208/
- Nigeria ultrasound rate: https://www.researchgate.net/publication/51782476_Awareness_of_information_expectations_and_experiences_among_women_for_obstetric_sonography_in_a_south_east_Nigeria_population 
- India ultrasound rate (proxy for Pakistan): https://dhsprogram.com/pubs/pdf/FR339/FR339.pdf

Update ultrasound utilization rates to be country-specific

---

docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst

This PR fills in the rest of the intrapartum decision tree inputs with placeholder values. Data points include:
- % of each type of facility with azithromycin (for Ethiopia only; but we do not have data on % of pregnancies receiving azithromycin by facility type) 
- RR of azithromycin on sepsis (from a BMGF-funded RCT) 
- % of pregnancies receiving antenatal corticosteroids by facility type (for Ethiopia only) 
- RR of c-section delivery on PPH
I added a row for the RR of c-sections on obstructed labor, but I'm not sure using an RR here makes sense, if we expect c-sections to completely remove the possibility of OL? Or do we expect some c-sections to still lead to some degree of OL? Also, I'm wondering if we should be grouping OL and uterine rupture together as we currently are. In doing …

Update intrapartum concept model (part 2)

---

docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst

In this PR I'm adding information on model run plans based on what I could find in [Nutrition Optimization docs](https://vivarium-research.readthedocs.io/en/latest/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.html#production-run-specifications), but I am not confident these are the right numbers for V&V runs. 
Syl, I've tagged you in this PR in case you have some insight as to what I should be doing for MNCNH V&V runs (vs. production runs?). And maybe this isn't the format for how we usually save draw and seed count for V&V in the docs? Maybe we can discuss more on Monday - thanks!

MNCNH V&V draw and seed count

---

docs/source/models/other_models/pregnancy/gbd_2021_mncnh/index.rst

Specify how to decide pregnancy outcomes (live birth, stillbirth, or partial term) on the pregnancy page, for the intrapartum model.

MNCNH: Add pregnancy outcomes to pregnancy page

---

docs/source/models/causes/maternal_disorders/gbd_2021_mncnh/index.rst
docs/source/models/causes/maternal_disorders/gbd_2021_mncnh/maternal_hemorrhage.rst
docs/source/models/causes/maternal_disorders/gbd_2021_mncnh/maternal_sepsis.rst
docs/source/models/causes/maternal_disorders/gbd_2021_mncnh/obstructed_labor.rst
docs/source/models/causes/maternal_disorders/index.rst

Adds a page for the new maternal disorders model, and adds stub pages for three subcauses. Also edits the table of contents in the maternal disorders index to display the subpages under the new main page.

MNCNH: Create page structure for maternal disorders

---

.github/workflows/build.yml
.readthedocs.yml
docs/source/conf.py
docs/source/models/causes/maternal_disorders/gbd_2021_mncnh/maternal_sepsis.rst

Add the [Sphinx Graphviz extension](https://www.sphinx-doc.org/en/master/usage/extensions/graphviz.html) so we can use a `.. graphviz::` directive to write code to generate Graphviz graphs directly in the docs.
I added a sample graph to the MNCNH maternal sepsis page to verify that the extension works.
If this gets merged, everyone will need to [install Graphviz](https://graphviz.org/download/) on their computer in order to render the docs without warnings/errors.

Add graphviz extension

---

docs/source/models/causes/maternal_disorders/gbd_2021_mncnh/maternal_sepsis.rst

Describes how to calculate YLLs and YLDs for maternal sepsis and other maternal infections in the MNCNH Portfolio sim.
I included a note about a limitation in our strategy: It won't correctly capture YLDs from infertility due to maternal sepsis. I'm not entirely confident in my logic arguing why I think our strategy will undercount averted YLDs, so it would be good to get some additional eyes on this.

MNCNH: Maternal sepsis burden

---

docs/source/models/causes/maternal_disorders/gbd_2021_mncnh/index.rst

Adds the GBD cause hierarchy for maternal disorders, and the subcause case definitions from the nonfatal methods appendix.

MNCNH: Maternal disorders cause hierarchy & subcause definitions

---

docs/source/models/causes/maternal_disorders/gbd_2021_mncnh/obstructed_labor.rst

This PR adds data tables to the OL cause model docs, and also updates the Restrictions Table to have YLDs continue accumulating for 95 plus group (instead of 50 to 54 age group).

Add Data Tables section to OL docs

---

docs/source/models/causes/maternal_disorders/gbd_2021_mncnh/obstructed_labor.rst

In lines 194-198, I state that 'cases of uncured or untreated fistulas generally increase with age', and I don't think this is correct based on get_draws() which shows fistula YLDs generally decreasing with age (See Fistula Impairment section in notebook [here](https://github.com/ihmeuw/vivarium_research_mncnh_portfolio/blob/main/data_prep/gbd2021_data_pulling.ipynb)). I left it in though because I wanted to make sure I would be correct in removing it - I'm not sure if this means we would still be undercounting YLDs or why fistula YLDs would be different than infertility YLDs caused by sepsis.

MNCNH obstructed labor Calculating Burden section

---

docs/source/models/causes/maternal_disorders/gbd_2021_mncnh/maternal_hemorrhage.rst

This PR uses sepsis and OL docs to fill out the Scope, Summary of modeling strategy, and Cause model diagram sections of the maternal hemorrhage docs.

Update vivarium modeling strategy for maternal hemorrhage

---

docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst

This PR describes observer requests for V&V of the intrapartum model. Instead of requesting state tables like we did for the pregnancy model, this requests count data. This PR also adds a list of the V&V checks we will do for the intrapartum model.

Update MNCNH concept model docs with intrapartum observer requests

---

.github/workflows/build.yml
.readthedocs.yml
docs/source/conf.py
docs/source/onboarding_resources/contributing/index.rst
requirements.txt

Upgrades us to latest stable version of Python and Sphinx. Build is passing and I manually inspected a smattering of pages on the local and RTD build and didn't see anything wacky. Verified that our CSS overrides were still working.

Upgrade Python and Sphinx

---

.readthedocs.yml

https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/

Add explicit configuration to readthedocs

---

docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst

These values are placeholders while we figure out how to find more reliable input data. As with CPAP, we have good facility data for Ethiopia, but not for Pakistan and Nigeria. Unlike with CPAP, we don't have a Cochrane Review providing us with an RR, but we could use this estimate from LiST, or copy their methods and calculate our own estimate of RR.

Update concept model with placeholder values for antibiotics for neonatal sepsis

---

requirements.txt

Workaround for https://github.com/spatialaudio/nbsphinx/issues/825#issuecomment-2670307450, addresses build failures in #1589 and #1595

Don't use sphinx 8.2.0 (yet)

---

docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst

With the observer bugfix, early neonatal ACMR is validating now: 
Next step is to look into the CSMRs!

Update VnV tracker with no-LBWSG and early NN observer bugfix runs 3.2 & 3.3

---

requirements.txt

Note: it's not important to rebuild your environment with this change, as we still aren't building with Sphinx 8.2; rather, the pin has just [been pushed upstream for now](https://github.com/spatialaudio/nbsphinx/pull/828).

Unpin Sphinx

---

docs/source/models/concept_models/vivarium_mncnh_portfolio/ai_ultrasound_module/module_document.rst
docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst
docs/source/models/intervention_models/neonatal/antibiotics_intervention.rst
docs/source/models/intervention_models/neonatal/cpap_intervention.rst

Our key data gaps are: 
- RR of neonatal antibiotics on sepsis mortality*
- CPAP and neonatal antibiotics baseline coverage by delivery facility type (OK data for Ethiopia, no data for Nigeria or Pakistan)
- Standard ultrasound baseline coverage at ANC (OK literature value for Ethiopia, questionable lit value for Nigeria, none for Pakistan)
- Delivery facility choice by preterm status (Good data for Pakistan, questionable data for Ethiopia, no data for Nigeria)
*I'm currently trying to track down where Abie got the placeholder value for neonatal antibiotics RR on sepsis. The value I found in wave 1 data seeking is actually for prenatal/parental antibiotics effect on neonatal sepsis, which is not what we're looking for.

Update data limitations based on wave 1 data review

---

docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst

As I was doing recent V&V tracking I realized it would be helpful to make these changes.
Summary of what I did in this PR:
1. Updated observers table to what matches current outputs
2. Added observer 7 to reflect information that looked like it was in the old observer table but that I did not see in the outputs
3. Moved repeated info to a "defaults" table (including locations, population size, and number of draws that were repeated for each model and the base directory for all model results)
4. Removed the "status" column from the model runs table because we can see which runs have gone through V&V already in the V&V table
5. Brought table format in line with concept model template
Questions for the team (don't necessarily need to be resolved in this PR, but just want to make a record): …

Clean up of MNCNH concept model

---

docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst
docs/source/models/concept_models/vivarium_mncnh_portfolio/intrapartum_interventions/module_document.rst
docs/source/models/concept_models/vivarium_mncnh_portfolio/maternal_disorders_module/module_document.rst
docs/source/models/intervention_models/intrapartum/azithromycin_intervention.rst
docs/source/models/intervention_models/intrapartum/index.rst

This PR adds a page for how we will model azithromycin in the intrpartum model.
Currently we only include the impact of azithromycin on maternal sepsis (as is supported by the most recent systematic review I found on the topic), but I did find a [2021 systematic review](https://pmc.ncbi.nlm.nih.gov/articles/PMC8436060/) that found a significant impact of intrapartum azithromycin on the incidence of preterm births and stillbirths (a decrease in preterm and an increase in stillbirths). The [2024 systematic review](https://bmcpregnancychildbirth.biomedcentral.com/articles/10.1186/s12884-024-06390-6#:~:text=Primary%20outcomes,-Among%20the%20six&text=The%20incidence%20of%20maternal%20sepsis%20was%20significantly%20lower%20in%20the,was%20analysed%20in%20three%20studies.) found no significant …

Write up documentation for azithromycin intervention

---

docs/source/models/intervention_models/neonatal/antibiotics_intervention.rst

Fix error/clarify variables in the PAF equation for neonatal antibiotics intervention. Mistake was due to my confusion over the "no intervention" risk factor format, but "intervention" coverage format which I find very confusing and a reminder that I would love to update this standard procedure on our team :) https://ihme.slack.com/archives/C014RDZA1GE/p1747695754198189

Fix antibiotics PAF equation

---

docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst

Things to note in this PR:
- I removed the 8.1.1 model run request that model 12.0 replaced but was not previously deleted
- Weird finding that neonatal mortality changes between models 8.3 (looks good) and 9.0 (underestimated) despite no obvious changes to the neonatal model between these runs
- Summary of V&V from model run 10.1 (removed LBWSG RR effect on NN enceph. to test whether that would fix cause-specific mortality calibration issues due to having negative other causes mortality risk)... I am not quite sure what to make of these findings and think we should pick the discussion back up at our next MNCNH RT meeting if not before

MNCNH vv update

---

docs/source/models/causes/maternal_disorders/gbd_2021_mncnh/maternal_sepsis.rst

Jira ticket: [SSCI-2068](https://jira.ihme.washington.edu/browse/SSCI-2068)
Edit the nodes in the maternal sepsis decision tree so that "dead" and "alive" become "died of sepsis" and "did not die of sepsis." This is more accurate because the simulant can die of another cause besides sepsis, but I had not considered this possibility when originally creating the diagram since this was the first maternal disorder we modeled.

MNCNH: Fix maternal sepsis decision tree nodes

---

docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst

I have a pretty strong hunch that one reason the CSMR of preterm birth looks too high is because [this less-than sign in the calculation of preterm prevalence](https://github.com/ihmeuw/vivarium_gates_mncnh/blob/2efd1d73af83e282351de115da7030083389cedb/src/vivarium_gates_mncnh/data/loader.py#L644) should be less-than-or-equal-to, since the interval is open on the right.

Add model run request for preterm prevalence bugfix

---

docs/source/models/risk_effects/hemoglobin/index.rst

- Renamed document so that it shows up in alphabetic order in the risk effects table of contents
- Reordered depression (which is ready) to come before hypertension (which is not ready) for clarity
- Removed outdated note that the depression cause model was not yet documented
- **Added specific get draws calls to pull relevant RRs and PAFs**
- **Noted several data issues with temporary solutions to ensure we don't block implementation, but that we should follow-up to confirm desired behavior (only thing blocking at the moment is the lack of PAF estimate for depressive disorders in GBD)**

Update hemoglobin risk effects doc

---

docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst
docs/source/models/intervention_models/mncnh_pregnancy/oral_iron_antenatal/oral_iron_antenatal.rst

We found a new Cochrane review for the IFA intervention, so this PR:
- Updates the reference for the IFA effect size on birthweight to be the new Cochrane review (which reported the same value as the previous review)
- Updates the effect size on maternal hemoglobin concentration (Note: both the 2015 and new 2024 Cochrane reviews focus on mainly high-income countries, with no representation of Sub-Saharan Africa, there is an RCT from Pakistan included in both though. I could note the limitation that this might overestimate effect size on Hb given SSA countries have higher rates of non-iron deficiency anemias, but I haven't yet!)

Update IFA documentation based on new Cochrane review

---

docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst

This is kind of half-finished, because I haven't yet addressed the V&V criteria of "Confirm LBWSG risk effects are working as expected."
But this was the main point of interest for this model, and 12.1 seems to have improved things substantially!
We think the remaining discrepancy may be an issue in our approach to calculating late neonatal PAFs.

Add model 12.1 V&V to table

---

docs/source/model_design/general_reference_material/bliss/race_ethnicity/index.rst

In this PR I update the results section in the race/ethnicity guide to include the recommendation from the sex/gender guide about how to give a detailed description of our methods with regard to race/ethnicity data. I also removed the 'Considering prior adjustments' section that there was a to-do note about, because it seems like it would maybe be duplicative with the section above.

Update results section recommendations in race/ethnicity guide 

---

docs/source/models/causes/alzheimers/presymptomatic_and_mci_gbd_2021/index.rst
docs/source/models/concept_models/vivarium_alzheimers/concept_model.rst

Changes the hazard function for the BBBM->MCI transition from a Gamma distribution to a Weibull distribution, with a larger mean and variance. Based on input from client.

Alzheimer's model 4.2: Switch to Weibull distribution

---

docs/source/model_design/vivarium_model_components/causes/index.rst
docs/source/models/causes/alzheimers/presymptomatic_and_mci_gbd_2021/index.rst
docs/source/models/concept_models/vivarium_alzheimers/concept_model.rst
docs/source/models/other_models/alzheimers_population/index.rst

Describes how to update our data to use the Alzheimer's proportion of the GBD 2023 dementia envelope, rather than using the GBD 2021 "Alzheimer's disease and other dementias" cause.
Also fills in the data sources table on the Alzheimer's population page, and removes the info about ACMR forecasts from that page since it's now included on the cause model page.
Note that we are still getting our CSMR and EMR from the GBD 2021 "Alzheimer's disease and other dementias" cause despite getting prevalence and incidence from DisMod. We should probably revisit this point when we circle back to adding mixed dementias to the model.

Alzheimer's Model 5 (use AD proportion of GBD 2023 dementia envelope)

---

docs/source/models/concept_models/vivarium_mncnh_portfolio/concept_model.rst
docs/source/models/concept_models/vivarium_mncnh_portfolio/hemoglobin_component/module_document.rst
docs/source/models/intervention_models/mncnh_pregnancy/oral_iron_antenatal/oral_iron_antenatal.rst

@hussain-jafari the key update here is that we've defined 2 parameters:
- "baseline_ifa_at_anc": the value that you already have in the artifact, to be used as the probability of coverage among simulant who attends ANC
- "baseline_ifa_overall": equal to baseline_ifa_at_anc * ANC1. To be used in the baseline calibrations ("ifa_deleted_hemoglobin") and then I think it's termed the "risk-specific shifts" in the existing implementation for BW and GA
Let me know if you have any questions!

Clarify baseline IFA parameters and general docs clean up
